### ISSUE TITLE
Latest version of gradle-versions-plugin is not available in Maven Central

### ISSUE THREAD

**Issue by deadmoto** [ben-manes/gradle-versions-plugin#99] opened 2016-04-11 18:41 UTC
As the title says, the latest version of this plugin is not available from Maven Central repository.
However, it is available from JCenter.
It would be nice to have it available in both repositories, as they are setup as default in Gradle.

**Comment by ben-manes** [comment] 2016-04-11 19:59
I'm neutral on this, since the plugin portal is where Gradle wants plugins deployed. That's hosted by JCenter, I believe.

@jochenberger if you want to do this, I can send you my credentials to enable their auto-sync feature.

**Comment by jochenberger** [comment] 2016-04-12 08:22
If that can be set up to happen automatically, I can do it. But we can also change the publishing mechanism to use *your* bintray repository again. However, that would mean that you have to do the releases.

**Comment by jaredsburrows** [comment] 2016-06-23 22:35
Use:
```
repositories {
    maven { url "https://plugins.gradle.org/m2/" } // Mirrors jcenter() and mavenCentral()
}
```
like
```
buildscript {
    repositories {
        maven { url "https://plugins.gradle.org/m2/" } // Mirrors jcenter() and mavenCentral()
    }

    dependencies {
        // Check for plugin updates
        classpath "com.github.ben-manes:gradle-versions-plugin:0.12.0"
    }
}

repositories {
    maven { url "https://plugins.gradle.org/m2/" } // Mirrors jcenter() and mavenCentral()
}
```

For now, the official gradle plugins mirrors both `mavenCentral()` and `jcenter()`.

**Comment by ben-manes** [comment] 2016-07-05 23:53
@jochenberger If you'd prefer having me to handle releases again please let me know the procedure. I enjoyed having an excuse to keep chatting with you, but I know its an inconvenience.

**Comment by jochenberger** [comment] 2016-07-06 06:48
I don't mind doing the releases, but I need some kind of trigger. I'm not actively following the issue tracker at the moment.
But if you like, we can change the bintray plugin configuration to publish to your repository again.

**Comment by ben-manes** [comment] 2016-07-06 06:53
I'm pretty inactive too and hopefully one day Gradle will support this feature natively. I ping'd you a few days ago on #97 and figured that got lost in the daily grind. I can email instead if you prefer. Its not a big deal to do it myself, but still enjoy the excuse.

**Comment by jochenberger** [comment] 2016-07-06 08:15
Sorry, I completely read that over. So, yes, I guess e-mails are way safer to catch my attention. ;-)
Doing a 0.13.0 now.

**Comment by gabrielittner** [comment] 2016-09-19 22:22
Any update on publishing 0.13.0 to central?

**Comment by ben-manes** [comment] 2016-09-19 22:24
What's the value add? I think we can set it up to sync automatically, but the plugin portal seems to be preferred.

**Comment by jaredsburrows** [comment] 2016-09-19 22:41
@gabrielittner @ben-manes 
Use the following to mirror both:
```
    repositories {
        maven { url "https://plugins.gradle.org/m2/" }
    }
```

**Comment by gabrielittner** [comment] 2016-09-19 22:57
Central doesn't allow anyone to publish to random group ids and artefacts on central can't be deleted. Both can happen on jcenter, which is why I generally try to avoid it.

**Comment by jaredsburrows** [comment] 2016-09-19 23:00
I disagree with the first part. I have never seen anyone make a duplicate of a library on jcenter before. Also, there is nothing wrong with deleting, ideally you should publish a new version.

**Comment by gabrielittner** [comment] 2016-09-19 23:01
@jaredsburrows There are unofficial versions of the android support lib on jcenter with `com.android.support` as groupId.

**Comment by ben-manes** [comment] 2016-09-19 23:02
Deleting and spoofing are poor, and a common reason for disliking npm. I'll send @jochenberger my credentials and, if he'd like, he can setup a JCenter sync. He's been kindly handling the releases.

**Comment by jaredsburrows** [comment] 2016-09-19 23:10
@gabrielittner Can you give an example? Google stores the support libraries and gradle plugins in jcenter.

**Comment by gabrielittner** [comment] 2016-09-19 23:24
@jaredsburrows The support libraries are distributed in a repository that is downloaded by the Android SDK manager. The Android gradle plugin adds that repository to the project. Everything published at http://jcenter.bintray.com/com/android/support/ is not uploaded by Google, e.g.: https://bintray.com/ligboy/maven/android-support-fragment
The Android gradle plugin is published to both jcenter and maven central.

**Comment by jaredsburrows** [comment] 2016-09-19 23:30
Thanks for the example.

@gabrielittner Yes I know the support libraries are distributed through the SDK manager. I meant https://developer.android.com/studio/releases/gradle-plugin.html#revisions - https://developer.android.com/studio/intro/update.html#download-with-gradle. "SDK auto-download: Gradle will attempt to download missing SDK packages that a project depends on." - http://tools.android.com/tech-docs/new-build-system.

**Comment by gabrielittner** [comment] 2016-09-19 23:41
The new mechanism is using the sdk manager or at least is downloading the same repository the sdk manager downloads (didn't look at the implementation). That's why you need to accept the license before it works.

**Comment by jaredsburrows** [comment] 2016-09-19 23:42
Yeah

Jared Burrows

*jaredsburrows@gmail.com <jaredsburrows@gmail.com>*
LinkedIn: https://www.linkedin.com/in/jaredsburrows

**Comment by ben-manes** [comment] 2016-09-19 23:44
I'm closing because this feels too much like bikeshedding a problem that's not ours. If you need security then I recommend setting up a private repository.

If @jochenberger decides to setup a sync, wonderful. But otherwise its not this project's responsibility.

**Closed by ben-manes** 2016-09-19 23:44 UTC
