### ISSUE TITLE
Failed to determine latest version when jmeter plugin is listed on classpath

### ISSUE THREAD

**Issue by zarry** [ben-manes/gradle-versions-plugin#111] opened 2016-07-27 20:46 UTC
Hey @ben-manes. Having some issues running this plugin when we have the jmeter-gradle-plugin included in our buildscript { dependencies { } }

Specifically 

```
buildscript {
    repositories {
      ...
    }
    dependencies {
       ...
       classpath "com.github.kulya:jmeter-gradle-plugin:1.3.4-2.13"
    }
}
```

When this is present a majority of our dependencies report "Failed to determine the latest version" Simply removing the plugin from the classpath and the apply plugin 'jmeter' line result in the dependencies being found properly. 

Any idea why including the jmeter plugin is breaking the dependency look up and version checks?

**Comment by ben-manes** [comment] 2016-07-27 20:49
It might be including an overly restrictive `resolutionStrategy` or mucking with the repositories. You can use `-i` to see the dependency report's error and also watch Gradle's resolution log statements.

**Comment by zarry** [comment] 2016-07-27 20:53
Thank you for the very prompt response!  I will continue poking around a bit.  Looks like the exception is cause of unresolved state? Likely related to a overly restrictive `resolutionStrategy`?

```
The exception that is the cause of unresolved state: Could not resolve org.gebish:geb-gradle:+.
 - org.gebish:geb-spock
The exception that is the cause of unresolved state: Could not resolve org.gebish:geb-spock:+.
 - org.codehaus.groovy:groovy-all
```

**Comment by ben-manes** [comment] 2016-07-27 21:07
The log should say which repositories the plugin is querying for the configuration. If its been messed with you'll spot that immediately.

Another case might be if, for some reason, it can only be resolved with `latest.{revision}` instead of `+`. Not sure why that would be the case with any version Gradle v2.2+, though.

**Comment by ben-manes** [comment] 2016-07-27 21:36
When I add this plugin to the [example](https://github.com/ben-manes/gradle-versions-plugin/blob/master/examples/build.gradle) there doesn't appear to be any problems. So you'll have to dig into your build logs a little deeper to uncover the fault. It doesn't seem the plugin alone is responsible, and might be something with your customizations (e.g. the configuration not having a repository list for some reason).

**Comment by zarry** [comment] 2016-07-29 18:33
Thanks @ben-manes I will poke around with this some more next week and update you if I have any questions.  I appreciate the investigation and quick responses!

**Comment by zarry** [comment] 2016-08-01 15:17
@ben-manes Have you tried clearly your ~/.gradle/modules-2/metadata directory?  I have found that once you have a successful run it finds things cached and provides proper updates but starting with a clean cache is causing issues.  I will still play around with this some more just crossed my mind this morning as to why you weren't able to recreate.

**Comment by ben-manes** [comment] 2016-08-01 16:34
Good point. That's more concerning as Gradle's cache shouldn't be affect resolution. This plugin takes the simple approach of resolving with + and reporting the difference. A configuration to restrict resolution will apply here too, so that's the most common problem. Since Gradle is doing the heavy lifting, any resolution issue would be expected for all your dependencies too.

**Comment by ben-manes** [comment] 2016-08-01 18:12
Just tried your approach on wifi and worked fine for me. Other than ensuring that you're on a current Gradle version, I don't have any new advice. If you can reproduce in a small build script that you can share, I'll help investigate.

**Comment by ben-manes** [comment] 2016-10-25 22:39
Closing since I couldn't reproduce. Please re-open if its still and issue. If you can provide a test case for me to debug with, that would be really helpful.

**Closed by ben-manes** 2016-10-25 22:39 UTC
