### ISSUE TITLE
RCx should not have precedence over RELEASE

### ISSUE THREAD

**Issue by tkruse** [ben-manes/gradle-versions-plugin#25] opened 2014-03-03 13:36 UTC
Hi,

not sure whether this is a valid report or what to do about it. I get:

    The following dependencies have later milestone versions:
     - org.springframework.data:spring-data-commons [1.7.0.RELEASE -> 1.7.0.RC1]
     - org.springframework.data:spring-data-mongodb [1.4.0.RELEASE -> 1.4.0.RC1]

However, release obviously is a later milestone than release candidate.

**Comment by jaredsburrows** [comment] 2015-04-26 01:11
How is this issue coming?

I am seeing with following with `gradlew dependencyUpdates`:

    The following dependencies exceed the version found at the milestone revision level:
     - org.codehaus.groovy:groovy-all [2.4.3 <- 2.4.0-beta-1]

If you go to `http://mvnrepository.com/artifact/org.codehaus.groovy/groovy-all`, you can clearly see that the `2.4.3` is a release that is *newer* than `2.4.0-beta-1`.

**Comment by ben-manes** [comment] 2015-04-26 01:30
@jaredsburrows That's a separate issue. This one is due to the comparison of between two __resolved__ dependencies (an issue with the Gradle/Ivy comparator). Your issue is that Gradle resolves the latest to the wrong dependency version.

I can reproduce your issue if I set my repository to `jcenter()`. If I include `mavenCentral()` it works as expected. The usual problem is that the remote `maven-metadata` is incorrect. We can see that's the case here, as the JCenter [metadata](https://jcenter.bintray.com/org/codehaus/groovy/groovy-all/maven-metadata.xml) ends at `2.4.0-beta-1` and the Maven Central [metadata](https://repo1.maven.org/maven2/org/codehaus/groovy/groovy-all/maven-metadata.xml) at `2.4.3`.

**Comment by jaredsburrows** [comment] 2015-04-26 03:58
@ben-manes  Should I create a separate issue for this?

Also, should I use both `jcenter()` and `mavenCentral()`? or just use `mavenCenral()` for this plugin?

**Comment by ben-manes** [comment] 2015-04-26 04:04
Its not the plugin's fault, its a JCenter problem and to a lesser extent Gradle's. You need to include `mavenCentral()` for your dependencies to have a more accurate analysis. The plugin uses Gradle to query all of the repositories, and if those repositories provide bad information then they need to be fixed. There's nothing I can do about it.

**Comment by ben-manes** [comment] 2015-04-26 04:05
Personally I use both `jcenter` and `mavenCentral`.

**Comment by jaredsburrows** [comment] 2015-04-26 05:02
@ben-manes  I tried adding `mavenCentral()` like you suggested along with `jcenter()` and the plugin no longer reports the wrong meta data. Thanks!

**Comment by ben-manes** [comment] 2015-06-24 03:55
Fixed in #63. You can now use component selection rules to customize the report.

**Closed by ben-manes** 2015-06-24 03:55 UTC
