### ISSUE TITLE
javax.annotation:jsr250-api

### ISSUE THREAD

**Issue by asfdfdfd** [ben-manes/gradle-versions-plugin#82] opened 2015-10-27 12:04 UTC
I'm using javax.annotation:jsr250-api library.

```provided 'javax.annotation:jsr250-api:1.0'```

After executing 'dependencyUpdates' receiving this message:

```
The following dependencies have later milestone versions:
 - javax.annotation:jsr250-api [1.0 -> 1.0-20050927.133100]
```

After changing  gradle string to:

```provided 'javax.annotation:jsr250-api:1.0-20050927.133100'```

and executing 'build' receiving:

```
> Could not find jsr250-api.jar (javax.annotation:jsr250-api:1.0-20050927.133100).
  Searched in the following locations:
      https://jcenter.bintray.com/javax/annotation/jsr250-api/1.0-20050927.133100/jsr250-api-1.0-20050927.133100.jar
```

There is really no jar, only pom.

**Comment by ben-manes** [comment] 2015-10-28 05:40
Unfortunately the [maven-metadata](https://jcenter.bintray.com/javax/annotation/jsr250-api/:maven-metadata.xml) has bad version as the latest release. A maven artifact doesn't have to be a Java binary dependency, but can be other types like zip archives. So there's not much we can do, and I'd expect Maven's dependency updates to act similarly (e.g. Maven Central shows the bad version as the latest).

You'd have to make the dependency ignored, so a dupe of #81.

**Closed by ben-manes** 2015-10-28 05:40 UTC
