### ISSUE TITLE
Gradle 3.0 deprecation warning when using component selection rule

### ISSUE THREAD

**Issue by henrik242** [ben-manes/gradle-versions-plugin#75] opened 2015-08-17 06:14 UTC
I need to use this hack to get the component selection rule work (see #68):

    tasks.'dependencyUpdates'.doFirst {
      allprojects { configurations { all { resolutionStrategy { componentSelection { all {
        ComponentSelection selection ->
            boolean rejected = ['alpha', 'beta', 'rc', 'cr', 'm', 'b'].any { qualifier ->
                selection.candidate.version ==~ /(?i).*[.-]${qualifier}[.\d-]*/
            }
            if (rejected) {
                selection.reject('Release candidate')
            }
      }}}}}}
    }

This makes Gradle complain:

    Changed strategy of configuration ':foo:bar' after it has been resolved. This behaviour has been deprecated and is scheduled to be removed in Gradle 3.0

**Comment by ben-manes** [comment] 2015-08-17 06:24
Interesting, thanks. I don't see this when i use Gradle 2.6 and apply the README's sample. Are you sure this isn't due to the hack you used in #68?

**Comment by henrik242** [comment] 2015-08-17 06:26
Oh, yes, definitely.  I thought I'd document it as an issue, but forgot to add the whole config.  I'll update the issue.

**Comment by ben-manes** [comment] 2015-08-17 06:28
Probably we can call this a duplicate of #68 then. That needs to be fixed so you wouldn't need the nasty workaround. Sorry I haven't gotten back to it yet.

**Comment by henrik242** [comment] 2015-08-17 06:31
Sure, no problem :)

**Closed** 2016-01-13 06:22 UTC
