### ISSUE TITLE
Question: Check for dependency release dates

### ISSUE THREAD

**Issue by yifanzou** [ben-manes/gradle-versions-plugin#232] opened 2018-05-24 21:39 UTC
Hi,

This is a great plugin that solves many practical problems. I am considering instead of checking versions, is it possible to compare the release dates between current package and the latest one? Versions could hardly reflect how old the current dependency is behind the new one, because the update rates are various. 

And a minor question, does this plugin only check dependency updates on Maven Central, or it also search for other public repositories?

Thanks

**Comment by ben-manes** [comment] 2018-05-24 21:49
Thanks!

This plugin queries the repositories you have setup in Gradle associated with the project's configuration. As in, plugins use the `classpath` configuration from the `buildscript` block, so that configuration is tied to the `repositories` within that block. Your `compileJava` configuration will be tied to the project's `repositories`, so that set will be used. We don't set any defaults or override any querying, which also means it will work with a private repository. In fact all this plugin does is use Gradle's APIs and merely scripts their infrastructure to print a report. Its surprisingly (and wonderfully) mundane.

Unfortunately release dates are not captured in the `maven-metadata.xml` that build tools use to query the repository versions. This merely has an optional `lastUpdated` set by the creator, meaning it can be fibbed and lacks a timezone. It may be good enough, though.

(Duplicate of #221)

**Closed by ben-manes** 2018-05-24 21:49 UTC
