### ISSUE TITLE
dependencyUpdates task sometimes hangs if using Spring's dependency management plugin 

### ISSUE THREAD

**Issue by cliffred** [ben-manes/gradle-versions-plugin#255] opened 2018-09-17 09:44 UTC
Since version 0.18.0 the versions plugin the dependencyUpdates task often hangs for minutes. After inspecting a couple of thread dumps it seems to be a combination of the versions plugin and [Spring's dependency management plugin](https://github.com/spring-gradle-plugins/dependency-management-plugin). 

I've created a simple repo (https://github.com/cliffred/versions-plugin-sample) with two build scripts: build-hang.gradle and build-success.gradle. They both use exactly the same dependencies, but build-hang uses the dependency-management plugin.

gradlew clean dependencyUpdates -b build-success.gradle is always successful, but 
gradlew clean dependencyUpdates -b build-hang.gradle sometimes hangs and Gradle outputs something like this for minutes:

```
> Resolve dependencies of :interfaces.facade:pti.interfaces.facade.service.ear:testImplementationCopy
> Resolve dependencies of :interfaces.facade:pti.interfaces.facade.service.ear:defaultCopy
> Resolve dependencies of :interfaces.facade:pti.interfaces.facade.service.ear:sonarlibrariesCopy
> Resolve dependencies of :interfaces.facade:pti.interfaces.facade.service.ear:testRuntimeClasspathCopy
> Resolve dependencies of :interfaces.facade:pti.interfaces.facade.service.ear:apiElementsCopy
> Resolve dependencies of :interfaces.facade:pti.interfaces.facade.service.ear:annotationProcessorCopy
> IDLE
> Resolve dependencies of :interfaces.facade:pti.interfaces.facade.service.ear:runtimeClasspathCopy
```

It seems to be a race condition as it does not always happen, the problem occurs more often in bigger projects.

I've attached some thread dumps from when the task hangs:
[stack1.txt](https://github.com/ben-manes/gradle-versions-plugin/files/2388027/stack1.txt)
[stack2.txt](https://github.com/ben-manes/gradle-versions-plugin/files/2388025/stack2.txt)
[stack3.txt](https://github.com/ben-manes/gradle-versions-plugin/files/2388026/stack3.txt)

**Comment by ben-manes** [comment] 2018-09-17 14:26
@wilkinsona should also take a look. Thanks for the details so we can dig in.

**Comment by wilkinsona** [comment] 2018-09-17 15:18
Thanks for the ping. I've managed to reproduce the problem a handful of times. Given that it only happens occasionally, my gut feel is that this is most likely to be a problem in Gradle rather than in either plugin.

Running with `--debug` doesn't help much. While it appears to be hung, the output looks like the following:

```
16:16:11.744 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
16:16:11.744 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
16:16:11.746 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
16:16:11.747 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
16:16:11.747 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
16:16:11.747 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
16:16:21.744 [DEBUG] [org.gradle.launcher.daemon.server.Daemon] DaemonExpirationPeriodicCheck running
16:16:21.744 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
16:16:21.744 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
16:16:21.744 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
16:16:21.744 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
16:16:21.744 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
16:16:21.745 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
16:16:31.742 [DEBUG] [org.gradle.launcher.daemon.server.Daemon] DaemonExpirationPeriodicCheck running
16:16:31.743 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
16:16:31.743 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
16:16:31.743 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
16:16:31.743 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
16:16:31.743 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
16:16:31.744 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
16:16:41.743 [DEBUG] [org.gradle.launcher.daemon.server.Daemon] DaemonExpirationPeriodicCheck running
16:16:41.743 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
16:16:41.743 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
16:16:41.743 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
16:16:41.744 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
16:16:41.744 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
16:16:41.744 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
16:16:51.743 [DEBUG] [org.gradle.launcher.daemon.server.Daemon] DaemonExpirationPeriodicCheck running
16:16:51.743 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
16:16:51.743 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
16:16:51.743 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
16:16:51.743 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
16:16:51.744 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
16:16:51.744 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
```

**Comment by wilkinsona** [comment] 2018-09-17 15:47
I've managed to have a look in the debugger when it's looping hard and consuming a lot of CPU. From what I can tell it's stuck in `TreeMap.put`. The map's size is 99 yet it appears to be looping indefinitely trying to position the new entry the comparator is called with the following:

- `configuration ':detachedConfiguration104'`, `configuration ':detachedConfiguration102'`.
It returns 2.
- `configuration ':detachedConfiguration104'`,  `configuration ':detachedConfiguration11'`.
It returns -1
- `configuration ':detachedConfiguration104'`,  `configuration ':detachedConfiguration100'`.
It returns 4
- `configuration ':detachedConfiguration104'`, `configuration ':detachedConfiguration102'`.
It returns 2.

At this point it's stuck in a loop. It looks like a bug in Gradle's comparator to me.

**Comment by ben-manes** [comment] 2018-09-17 16:08
Thanks @wilkinsona! Sorry I haven’t had a chance to investigate myself.

In v18 we resolve configurations concurrently using a threadpool. It sounds to me like the callback from your plugin could cause Gradle to deadlock, e.g. within its cache where lookups depending on each other. That would be a Gradle bug, of course, with it needing to detect those cases and handle them. The immediate change on our end might be to allow the parallel resolution to be disabled. Since its likely a Gradle bug, we can try to get their team to take a look and maybe fix it long term.

**Comment by ben-manes** [comment] 2018-09-17 16:26
Do you think then maybe `TreeMap` was corrupted by concurrent access? One can make `HashMap` infinite loop in that way.

**Comment by wilkinsona** [comment] 2018-09-17 16:27
Hah! Yeah, I do. I was just in the process of writing that when your comment appeared.

**Comment by ben-manes** [comment] 2018-09-17 16:32
Can you open a bug with Gradle, regarding the lines of code (since you know which `TreeMap`, etc) and reference this one? Hopefully its something as simple a using `synchronizedMap` which shouldn't be slow in the normal cases.

**Comment by wilkinsona** [comment] 2018-09-18 09:59
I've opened [a Gradle issue](https://github.com/gradle/gradle/issues/6796).

**Comment by ben-manes** [comment] 2018-09-18 13:18
Thanks you!

**Comment by big-guy** [comment] 2018-09-18 22:09
Hi @ben-manes,

The Gradle project model isn't thread safe, so plugins that need access to it need to go through Gradle APIs that control access or otherwise be careful when accessing another project's state. Internally, when executing tasks and resolving configurations, Gradle manages the threads that are trying to access a given project. A plugin should be safe to assume that it's not going to be accessed concurrently (e.g., plugins are applied once, tasks are configured in a single-threaded way, etc) unless it explicitly sets up something shared across projects. I think the gradle-versions-plugin is triggering cross-project concurrency problems by working outside what Gradle normally controls.

I see two issues in `DependencyUpdates`:

Configurations are being resolved in non "Gradle threads" in parallel:
https://github.com/ben-manes/gradle-versions-plugin/blob/master/src/main/groovy/com/github/benmanes/gradle/versions/updates/DependencyUpdates.groovy#L69-L80

If you wanted to keep the parallel nature of checking for updates, I think you could do that separately after all of the configurations have been resolved sequentially in the task's thread.

Configurations from other projects are being resolved in the root project directly. 
https://github.com/ben-manes/gradle-versions-plugin/blob/master/src/main/groovy/com/github/benmanes/gradle/versions/updates/DependencyUpdates.groovy#L51-L53

This is the source of lots of problems as this bypasses many checks Gradle has on project state. We're adding a deprecation/error for this soon. I think a simple fix would be to restrict the DependencyUpdate task to only work on the configurations in the project it's declared in.  The root project can aggregate the reports by linking to them. The important thing is to avoid reaching into the other project. I think this would return some amount of parallelization as well.

I noticed this odd line too:
https://github.com/ben-manes/gradle-versions-plugin/commit/bb5f126e57cf966e2515f3f37cb22897aa6f1d28

I think this is unnecessary or at least doesn't make sense.  Once we've reached the point of task execution, it doesn't make sense to evaluate more projects.  I think this is may be a symptom of the kind of problems you'll see reaching across projects.  You can't be sure it's in the right state or something isn't concurrently modifying it.

HTH.

**Comment by ben-manes** [comment] 2018-09-18 23:03
Thanks @big-guy!

We added concurrency in v18, so very recently as it appeared safe. 

> Configurations are being resolved in non "Gradle threads" in parallel...

Would using the Worker API be more appropriate to ensure Gradle controls the threads? Or would that still run into these types of problems?

> If you wanted to keep the parallel nature of checking for updates, I think you could do that separately after all of the configurations have been resolved sequentially in the task's thread.

Would this not defeat the purpose, as resolving the configurations is slow? We could definitely revert out the concurrency and be slower, but since it was a common complaint the PR was accepted.

> Configurations from other projects are being resolved in the root project directly. This is the source of lots of problems as this bypasses many checks Gradle has on project state. We're adding a deprecation/error for this soon.

I did write that code originally for Gradle ~1.0, so no surprise it was both bad practice on my part and eventually deprecated :)

> The root project can aggregate the reports by linking to them. The important thing is to avoid reaching into the other project. I think this would return some amount of parallelization as well.

Do you have a good example of this? I have only done similar using jacoco aggregate reports, which reads the result files to combine them together. I'm not much of a plugin guru by merely writing a few popular ones and only this one failed to be handed off somewhere better.

> I noticed this odd line too: bb5f126

Yes, I never understood it but the PR claimed it fixed a bug fix and didn't appear to hurt in my testing. I'm fine removing.

**Comment by oehme** [comment] 2018-10-01 16:17
> after all of the configurations have been resolved sequentially in the task's thread.

It shouldn't be necessary to resolve sequentially. Dependency resolution is supposed to be paralle-safe. If that fails for some reason, then that's a bug in Gradle. We are probably missing some guards around user-provided hooks e.g. `beforeResolve {}`.

**Closed** 2019-02-27 06:11 UTC

**Comment by MartinX3** [comment] 2019-03-01 09:37
Thank you, that fixed my loop problem after removing the .gradle folder contents (except init.gradle).
But of course, it's now slower since we're missing parallel downloads. :)
