### ISSUE TITLE
False posivite with transitive dependency

### ISSUE THREAD

**Issue by icecuber** [ben-manes/gradle-versions-plugin#152] opened 2017-03-24 16:33 UTC
![ben-manes-bug](https://cloud.githubusercontent.com/assets/1236294/24303711/4e7a5374-10b7-11e7-96f0-fe7a39cd7443.png)

as you can see in the image in my main project i specify groovy 2.4.10, 
while in some dependecy library i specify 'older' 2.4.9, the same happens with slf4j,

if needed i can provide all 3 build.gradle files!

**Comment by ben-manes** [comment] 2017-03-24 16:37
If you have a multi-project build, one project may be using the older dependency. It would then list both separately so that you can ensure project-wide you are up to date. That might be the cause of the confusing output.

The build files, especially if we can run them, would be helpful so that I can give you an exact answer.

**Comment by icecuber** [comment] 2017-03-27 07:15
I zipped the main project build and the 2 libs build, i added also the generated pom,
i noticed that groovy is set to 2.4.8 in one build, i don't know why it says
 - org.codehaus.groovy:groovy [2.4.9 -> 2.4.10]
[finmatica-GPs-ZK-build.zip](https://github.com/ben-manes/gradle-versions-plugin/files/871683/finmatica-GPs-ZK-build.zip)
[finmatica-ifw-build.zip](https://github.com/ben-manes/gradle-versions-plugin/files/871684/finmatica-ifw-build.zip)
[main_proj_build.zip](https://github.com/ben-manes/gradle-versions-plugin/files/871685/main_proj_build.zip)

**Comment by ben-manes** [comment] 2017-03-27 08:47
When I check `gradle dependencies` it does show `2.4.10` and if I add `ext['groovy.version'] = '2.4.10'` to the build file then the dependency update report shows as expected. 

Since this is a Spring Boot project, from other issues I've learned that it has its own dependency management approach. This can sometimes cause surprising interactions, which this is another case of. The [Spring BOM](http://search.maven.org/#artifactdetails%7Corg.springframework.boot%7Cspring-boot-dependencies%7C1.5.2.RELEASE%7Cpom) is on `2.4.9`, the BOM is applied globally, and your override is only applied to the `compile` configuration. When your version is set globally as above it is applied to every configuration and the report is correct.

This plugin copies the configurations before resolving them. This is to avoid excessive work (e.g. resolving transitives) and isolate modifications from leaking into your build. The copy then has a different configuration name, causing Spring's overrides to not be detected.That's due to `beforeResolve` listeners not being copied, which is [fixed](https://github.com/gradle/gradle/issues/1567) in the next Gradle release. When I use the nightly snapshot the report is correct.

The fix is to either make versions updates global or wait until the next Gradle release.

**Closed** 2017-03-29 08:46 UTC
