### ISSUE TITLE
Cannot detect libraries from jitpack.io

### ISSUE THREAD

**Issue by tasomaniac** [ben-manes/gradle-versions-plugin#79] opened 2015-10-08 08:05 UTC
Plugin cannot detect libraries from Jitpack.io

**Comment by ben-manes** [comment] 2015-10-08 20:56
This is by design of [jitpack.io](jitpack.io). They do not provide the metadata that maven/ivy repositories provide (e.g. maven_metadata.xml) so a resolution cannot be performed client-side. Instead they build on-demand, cache, and serve the contents. Since they are not providing a fully compliant repository, just a partial that is good enough, I don't think any tool can search it for updates.

So unless this works in Maven but not here, I don't think its an issue we can resolve on our side.

**Comment by tasomaniac** [comment] 2015-10-08 21:26
I think the versioning in jitpack.io is directly coming from releases in github project. It uses release tags in github.

I don't know if it is worth it but we may use github's api to check the versions of the projects. Just like how jitpack is doing.

**Comment by ben-manes** [comment] 2015-10-08 21:33
jitpack uses github releases or a commit hash. I think the right fix would be for them to fully emulate a maven repository, since that's what its claiming to be. To do so would mean providing a `maven_metadata.xml` in addition to the artifacts. Since they query github its reasonable for them to dynamically construct this in addition to the rest of the artifact information. It would then work properly in all the build tools (maven, sbt, ivy, etc). So I think you should file this bug on their queue.

**Comment by ben-manes** [comment] 2015-10-08 22:55
Verified that Maven cannot discover updates either (`mvn versions:display-dependency-updates`) for a jitpack-only dependency.

**Comment by tasomaniac** [comment] 2015-10-09 07:18
Good point and it makes sense. Thank you for opening the issue. Let's see their response.

**Comment by jitpack-io** [comment] 2015-10-09 08:39
Hi @tasomaniac 
Would it be possible to post more details in https://github.com/jitpack/jitpack.io/issues/227?

**Comment by tasomaniac** [comment] 2015-10-09 09:21
Returning back to the original issue. I don't think that it is related to @jitpack-io 

When I run `./gradlew dependencyUpdates` from the command line, it actually shows that there is an update available. 

![screen shot 2015-10-09 at 12 20 18](https://cloud.githubusercontent.com/assets/763339/10390256/2666e530-6e80-11e5-8cde-349cb6134473.png)

But when I run the task within Android Studio, it continues to report all the other libraries but not this one.

**Comment by ben-manes** [comment] 2015-10-09 18:05
Sorry that I misidentified the issue and added the details on jitpack's tracker. I think they can close it out as not a bug on their side. The issue appears to be due to #66 which shows that Gradle's `RepositoryHandler` is broken and we have to avoid using it. I'll try to work through the backlog of tasks over the weekend and push out a new release.

I think that Android Studio breaks due to #66. Most likely it is trying to dynamically add the SDK location as another repository. However Gradle's broken duplication detection logic results in some repositories being dropped. By random order this is jitpack, but in #78 it could be the SDK failing to be added.

The right fix on our side is to stop aggregating and trying to provide a fuller view of what updates are available. By luck Gradle's own usages doesn't hit this bug because `addAll` generates duplicates and our use of `add` incorrectly identifies duplicates. We added this back in #2, but its become broken in current versions of Gradle and we've been unsuccessful in getting it addressed by the Gradle team.

**Comment by ben-manes** [comment] 2016-01-13 04:34
Resolved when fixing #66 (duplicate)

**Closed by ben-manes** 2016-01-13 04:34 UTC

**Comment by tasomaniac** [comment] 2016-01-13 05:49
Great, when is it going to be released?

**Comment by ben-manes** [comment] 2016-01-13 06:20
This week. I finally caved to embarrassment of leaving this in such a state, and am trying to crunch through all the issues before I lose steam.

**Comment by ben-manes** [comment] 2016-01-13 23:44
Forgot to mention update that this was released last night.

**Comment by tasomaniac** [comment] 2016-01-14 06:23
Thank you. I will try today.
