### ISSUE TITLE
Can I get 2/3 level report

### ISSUE THREAD

**Issue by igreenfield** [ben-manes/gradle-versions-plugin#193] opened 2017-11-06 09:30 UTC
In SBT plugin I get report that look like:
```
group:name                                    current            minor      major
com.typesafe.akka:akka-stream                 : 2.4.18        -> 2.4.20  -> 2.5.6
```

Can I get such report?

thanks

**Comment by vanniktech** [comment] 2017-11-06 09:44
Possibly a dupe of #96

**Comment by vanniktech** [comment] 2018-02-26 17:55
Closing in favor of #96

**Closed by vanniktech** 2018-02-26 17:55 UTC
Labels: enhancement
