### ISSUE TITLE
Support dependency configurations from java-library

### ISSUE THREAD

**Issue by pkubowicz** [ben-manes/gradle-versions-plugin#127] opened 2017-02-01 14:57 UTC
Gradle 3.4 RC introduces 'java-library' as a replacement for 'java'. Running 'dependencyUpdates' on such a project produces errors:
```
Failed to resolve ::api
Failed to resolve ::apiElements
Failed to resolve ::implementation
Failed to resolve ::runtimeElements
Failed to resolve ::runtimeOnly
Failed to resolve ::testImplementation
Failed to resolve ::testRuntimeOnly
```

Also, the plugin fails to check the new configurations.

To reproduce use `build.gradle` with
```
plugins {
    id 'com.github.ben-manes.versions' version '0.13.0'
    id 'com.github.johnrengelman.shadow' version '1.2.3'
}

apply plugin: 'java-library'

repositories {
    jcenter()
}

dependencies {
    api 'org.slf4j:slf4j-api:1.7.0'
    implementation 'com.google.guava:guava:19.0'
    compileOnly 'javax.servlet:javax.servlet-api:3.0.1'
    runtimeOnly 'ch.qos.logback:logback-classic:1.1.0'

    testImplementation 'junit:junit:4.10'
    testCompileOnly 'org.projectlombok:lombok:1.16.0'
    testRuntimeOnly 'org.slf4j:log4j-over-slf4j:1.7.0'
}
```

Each dependency in this file (except for the versions plugin) is outdated and should be reported. Currently only plugins, `compileOnly` and `runtimeOnly` are checked.

**Comment by ben-manes** [comment] 2017-02-01 17:20
This is because Gradle disallows resolving those configurations (see #125). I don't know why they did that. I'm hoping that cloning and setting the flag to allow will bypass this. We should probably ask to find out why, in case they'd prefer to revert in rc2/

**Comment by pkubowicz** [comment] 2017-02-01 19:06
Have you asked them? Do you need some help?

**Comment by ben-manes** [comment] 2017-02-01 19:09
[Yep](https://discuss.gradle.org/t/gradle-3-4-rc1-is-now-available-for-testing/21351/7?u=benjamin_manes). I'm a little concerned that `validateMutation` will reject it, but I haven't tested it yet.

**Comment by ben-manes** [comment] 2017-02-03 01:39
Adding @jochenberger, @oehme

Two approaches seem to work. Both seem a little hacky.

__Disable Restriction__
```
configuration = configuration.copyRecursive().setTransitive(false)
configuration.setCanBeResolved(true)
```
This calls a method only available in Gradle 3.3, so we'd have to check if the method is present first. I could also imagine this setting is disallowed later as perhaps not intended to be modified.

__Query with Detatched Configuration__
```
configuration = project.configurations.detachedConfiguration().extendsFrom(configuration)
```
and replace all usages of `configuration.dependencies` with `configuration.allDependencies`.

My concern here is that I have had poor experiences with copying and detached in the past. Now using a super configuration brings in another scenario that likely has bugs. In the past this has been unfixed bugs in repository handling and lately with [dependency-management-plugin/](https://github.com/spring-gradle-plugins/dependency-management-plugin/) interaction with resolution strategies (caused by bugs in configuration copying). But I think this is more inline with @oehme's intent as he refactors `Configuration` into multiple distinct concepts.

---

Using the example shows both approaches work.

```
------------------------------------------------------------
: Project Dependency Updates (report to plain text file)
------------------------------------------------------------

The following dependencies exceed the version found at the milestone revision level:
 - com.github.ben-manes:gradle-versions-plugin [0.14.0-SNAPSHOT <- 0.13.0]

The following dependencies have later milestone versions:
 - com.google.guava:guava [19.0 -> 21.0]
 - javax.servlet:javax.servlet-api [3.0.1 -> 4.0.0-b01]
 - junit:junit [4.10 -> 4.12]
 - org.slf4j:log4j-over-slf4j [1.7.0 -> 1.7.22]
 - ch.qos.logback:logback-classic [1.1.0 -> 1.1.9]
 - org.projectlombok:lombok [1.16.0 -> 1.16.12]
 - org.slf4j:slf4j-api [1.7.0 -> 1.7.22]
```

**Comment by oehme** [comment] 2017-02-03 09:55
I'd go with the detached configuration approach, as it is closer to where we want to go in the long run (having a "Query" concept). If there are bugs handling detached Configurations, please let us know.

> replace all usages of configuration.dependencies with configuration.allDependencies

I did a quick search and couldn't find usages of `configuration.dependencies` in this plugin. Did I miss something? As far as I can see you are using the resolved configuration (which makes sense, since otherwise you wouldn't get the actual selected versions).

**Comment by oehme** [comment] 2017-02-03 09:59
Nevermind, GitHub search is broken, I found the places you were referring to.

**Comment by oehme** [comment] 2017-02-03 10:04
You won't need to change to `allDependencies`. You can always call `Configuration.getDependencies`, even on ones that are not intended to be resolved. This method will give you the declared dependencies and you'll want to keep calling that on the original one supplied by the user.

**Comment by jochenberger** [comment] 2017-02-07 08:06
There's not much I can contribute here in terms of what the best approach might be. But what I take away from this is that we should rewrite the tests to use TestKit to make it easier to test against different Gradle versions.

**Comment by jochenberger** [comment] 2017-02-07 09:28
See #129

**Comment by ben-manes** [comment] 2017-02-07 18:58
Thanks @oehme and @jochenberger.

We'll use the detatched configuration method. I'll try to find the time to wrap that up.

**Comment by ben-manes** [comment] 2017-02-08 02:49
I have a draft that passes the examples (this one, and in examples folder). But it fails on two unit tests, so some debugging is needed. It fails with a custom component selection rule and @jochenberger's TestKit tests. I suspect the detatched configuration isn't honoring the super configuration's resolution strategies which is causing the problems.

**Comment by jochenberger** [comment] 2017-02-08 06:56
You could just create a PR. Travis should build them and we can inspect the build failure and try to fix it.

**Comment by ben-manes** [comment] 2017-02-08 06:59
Travis builds all branches, but I can add one if it's helpful to iterate on.

**Comment by oehme** [comment] 2017-02-08 07:53
Resolution strategies only work on the configuration they are declared on indeed. If you need them then a copy is the only way.

**Comment by ben-manes** [comment] 2017-02-08 07:57
Yes, we try to honor the build's configuration. So we'll have to use the `setCanBeResolved(true)` approach.

**Comment by jochenberger** [comment] 2017-02-08 09:43
See #137 for a new PR.

**Closed** 2017-02-08 09:47 UTC
