### ISSUE TITLE
New resolution  strategy doesn't work

### ISSUE THREAD

**Issue by timja** [ben-manes/gradle-versions-plugin#344] opened 2019-09-26 09:12 UTC
Project used is:
https://github.com/hmcts/draft-store (latest commit at time of writing is 565c2f0d0e95bd36f161282aef3a72d0b41f05e7)
but I've heard of the same issues on other applications

```
$ g --version

------------------------------------------------------------
Gradle 5.6.2
------------------------------------------------------------

Build time:   2019-09-05 16:13:54 UTC
Revision:     55a5e53d855db8fc7b0e494412fc624051a8e781

Kotlin:       1.3.41
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.14 compiled on March 12 2019
JVM:          1.8.0_222 (AdoptOpenJDK 25.222-b10)
OS:           Mac OS X 10.14.6 x86_64
```

```
dependencyUpdates {
  resolutionStrategy {
    componentSelection {
      all {
        if (isNonStable(candidate.version) && !isNonStable(currentVersion)) {
          reject('Release candidate')
        }
      }
    }
  }
}
```

```
Caused by: org.gradle.internal.metaobject.AbstractDynamicObject$CustomMessageMissingMethodException: Could not find method isNonStable() for arguments [2.9.10] on object of type com.github.benmanes.gradle.versions.updates.resolutionstrategy.ResolutionStrategyWithCurrent.
        at org.gradle.internal.metaobject.AbstractDynamicObject.methodMissingException(AbstractDynamicObject.java:182)
        at org.gradle.internal.metaobject.ConfigureDelegate.invokeMethod(ConfigureDelegate.java:86)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeOnDelegationObjects(ClosureMetaClass.java:398)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:338)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:821)
        at groovy.lang.GroovyObjectSupport.invokeMethod(GroovyObjectSupport.java:44)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeOnDelegationObjects(ClosureMetaClass.java:398)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:338)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:821)
        at groovy.lang.GroovyObjectSupport.invokeMethod(GroovyObjectSupport.java:44)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeOnDelegationObjects(ClosureMetaClass.java:398)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:338)
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:68)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:168)
        at build_4qzqkcuwnnyxrd4gdg1gcf3u7$_run_closure13$_closure31$_closure32$_closure33.doCall(/Users/timja/projects/hmcts/draft-store/build.gradle:138)
        at sun.reflect.GeneratedMethodAccessor360.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:104)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:326)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:41)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127)
        at com.github.benmanes.gradle.versions.updates.resolutionstrategy.ComponentSelectionRulesWithCurrent$2.execute(ComponentSelectionRulesWithCurrent.groovy:37)
        at com.github.benmanes.gradle.versions.updates.resolutionstrategy.ComponentSelectionRulesWithCurrent$2.execute(ComponentSelectionRulesWithCurrent.groovy)
        at org.gradle.internal.rules.NoInputsRuleAction.execute(NoInputsRuleAction.java:38)
        at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.ComponentSelectionRulesProcessor.processRule(ComponentSelectionRulesProcessor.java:84)
        ... 207 more
```

```

```
dependencyUpdates {
  // Example 2: disallow release candidates as upgradable versions from stable versions
  rejectVersionIf {
    isNonStable(candidate.version) && !isNonStable(currentVersion)
  }
}

```
Caused by: groovy.lang.MissingPropertyException: Could not get unknown property 'candidate' for task ':dependencyUpdates' of type com.github.benmanes.gradle.versions.updates.DependencyUpdatesTask.
        at org.gradle.internal.metaobject.AbstractDynamicObject.getMissingProperty(AbstractDynamicObject.java:84)
        at org.gradle.internal.metaobject.ConfigureDelegate.getProperty(ConfigureDelegate.java:130)
        at org.codehaus.groovy.runtime.InvokerHelper.getProperty(InvokerHelper.java:190)
        at groovy.lang.Closure.getProperty(Closure.java:298)
        at org.codehaus.groovy.runtime.InvokerHelper.getProperty(InvokerHelper.java:190)
        at groovy.lang.Closure.getPropertyTryThese(Closure.java:319)
        at groovy.lang.Closure.getPropertyOwnerFirst(Closure.java:313)
        at groovy.lang.Closure.getProperty(Closure.java:302)
        at org.codehaus.groovy.runtime.callsite.PogoGetPropertySite.getProperty(PogoGetPropertySite.java:49)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGroovyObjectGetProperty(AbstractCallSite.java:309)
        at build_4qzqkcuwnnyxrd4gdg1gcf3u7$_run_closure13$_closure31.doCall(/Users/timja/projects/hmcts/draft-store/build.gradle:137)
        at sun.reflect.GeneratedMethodAccessor373.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:104)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:326)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
        at groovy.lang.Closure.call(Closure.java:411)
        at org.codehaus.groovy.runtime.ConvertedClosure.invokeCustom(ConvertedClosure.java:50)
        at org.codehaus.groovy.runtime.ConversionHandler.invoke(ConversionHandler.java:122)
        at com.sun.proxy.$Proxy47.reject(Unknown Source)
        at com.github.benmanes.gradle.versions.updates.resolutionstrategy.ComponentFilter$reject.call(Unknown Source)
        at com.github.benmanes.gradle.versions.updates.DependencyUpdatesTask$_rejectVersionIf_closure2$_closure3$_closure4.doCall(DependencyUpdatesTask.groovy:102)
        at sun.reflect.GeneratedMethodAccessor197.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:104)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:326)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:41)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127)
        at com.github.benmanes.gradle.versions.updates.resolutionstrategy.ComponentSelectionRulesWithCurrent$2.execute(ComponentSelectionRulesWithCurrent.groovy:37)
        at com.github.benmanes.gradle.versions.updates.resolutionstrategy.ComponentSelectionRulesWithCurrent$2.execute(ComponentSelectionRulesWithCurrent.groovy)
        at org.gradle.internal.rules.NoInputsRuleAction.execute(NoInputsRuleAction.java:38)
        at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.ComponentSelectionRulesProcessor.processRule(ComponentSelectionRulesProcessor.java:84)
        ... 207 more
```

**Comment by jmfayard** [comment] 2019-09-26 09:27
@timja 
`Could not find method isNonStable()` is not a bug. 
There is no standard to what is considered a stable version, so you have to define your own in the build, and you can use the one of the README as a starting point.

For the second error, please have a look at the bottom of this issue. Not sure what's the status is.
https://github.com/ben-manes/gradle-versions-plugin/issues/325

**Comment by bric3** [comment] 2019-09-26 09:30
@timja here's my task configuration, hoping that helps :

```gradle
dependencyUpdates {
    def isNonStable = { String version ->
        def stableKeyword = ['RELEASE', 'FINAL', 'GA'].any { qualifier -> version.toUpperCase().contains(qualifier) }
        def regex = /^[0-9,.v-]+$/
        return !stableKeyword && !(version ==~ regex)
    }
    def isForbiddenMajor = { String candidateGroup, String candidateVersion ->
        boolean forbiddenMajor = [
                'org.springframework.boot'    : '2',
                'org.springframework.restdocs': '2',
                'org.springframework'         : '5',
                'io.rest-assured'             : '4',
                'org.asciidoctor.convert'     : '1'  // ignore next asciidoc plugin as spring-rest-doc not compatible with it yet
        ].any { group, version ->
            candidateGroup == group && !candidateVersion.startsWith(version)
        }
        return forbiddenMajor
    }

    rejectVersionIf { selection ->
        return (isNonStable(selection.candidate.version) && !isNonStable(selection.currentVersion)) ||
               isForbiddenMajor(selection.candidate.group, selection.candidate.version)
    }

    revision = "release"
    checkForGradleUpdate = true
    gradleReleaseChannel = "current"
}
```

**Comment by timja** [comment] 2019-09-26 09:36
> @timja
> `Could not find method isNonStable()` is not a bug.
> There is no standard to what is considered a stable version, so you have to define your own in the build, and you can use the one of the README as a starting point.
> 
> For the second error, please have a look at the bottom of this issue. Not sure what's the status is.
> #325

I see, while there is no standard, dependabot does a pretty good job of it.
It would be good in my opinion to provide a realistic default and let someone customise it:
https://github.com/dependabot/dependabot-core/blob/4b53b6624b3e0a6fc7229257922cd510f2eacd8e/gradle/lib/dependabot/gradle/version.rb#L14

**Comment by jmfayard** [comment] 2019-09-26 09:40
@timja 
It's in the README.md!

```groovy
def isNonStable = { String version ->
  def stableKeyword = ['RELEASE', 'FINAL', 'GA'].any { it -> version.toUpperCase().contains(it) }
  def regex = /^[0-9,.v-]+$/
  return !stableKeyword && !(version ==~ regex)
}
```

**Comment by timja** [comment] 2019-09-26 09:42
@bric3 thank you,
I missed the `selection` named bit, either the README needs an update or the code fixed.

I went with this:
```
dependencyUpdates {
  def isNonStable = { String version ->
    def stableKeyword = ['RELEASE', 'FINAL', 'GA'].any { qualifier -> version.toUpperCase().contains(qualifier) }
    def regex = /^[0-9,.v-]+$/
    return !stableKeyword && !(version ==~ regex)
  }
  rejectVersionIf { selection -> // <---- notice how the closure argument is named
    return isNonStable(selection.candidate.version) && !isNonStable(selection.currentVersion)
  }
}
```

@jmfayard it may be in the README but it's in a separate block to the main `dependencyUpdates` section, I missed it, I also asked on my team and other people had encountered this as well...

**Comment by jmfayard** [comment] 2019-09-26 09:46
The thing about having to use `selection` is that it should not be necessary, it's not necessary in Kotlin, and I am not sure why that doesn't work in Groovy. So this is more a bug fix. 

But if there is anything that can be improved in the README, feel free to send a pull-request

**Comment by bric3** [comment] 2019-09-26 09:57
@jmfayard in groovy if the closure argument is not explicitly named, the language default its name to `it, thus `candidate` and `currentVersion` must be prefixed by `it`.
I believe it's the same with Kotlin.

**Comment by timja** [comment] 2019-09-26 10:01
@bric3 do you mean this?
```
dependencyUpdates {
  def isNonStable = { String version ->
    def stableKeyword = ['RELEASE', 'FINAL', 'GA'].any { qualifier -> version.toUpperCase().contains(qualifier) }
    def regex = /^[0-9,.v-]+$/
    return !stableKeyword && !(version ==~ regex)
  }
  rejectVersionIf {
    return isNonStable(it.selection.candidate.version) && !isNonStable(it.selection.currentVersion)
  }
}
```

(doesn't work for me)

**Comment by bric3** [comment] 2019-09-26 10:03
@timja remove `selection` ;)

```gradle
dependencyUpdates {
  def isNonStable = { String version ->
    def stableKeyword = ['RELEASE', 'FINAL', 'GA'].any { qualifier -> version.toUpperCase().contains(qualifier) }
    def regex = /^[0-9,.v-]+$/
    return !stableKeyword && !(version ==~ regex)
  }
  rejectVersionIf {
    return isNonStable(it.candidate.version) && !isNonStable(it.currentVersion)
  }
}
```

**Comment by ben-manes** [comment] 2019-09-28 16:43
Closing, thanks for the doc fix.

**Closed by ben-manes** 2019-09-28 16:43 UTC
