### ISSUE TITLE
Handle non-jar / metadata-only artifacts

### ISSUE THREAD

**Issue by sschuberth** [ben-manes/gradle-versions-plugin#424] opened 2020-09-08 07:17 UTC
In regards to `com.github.ajalt.clikt:clikt`, this is because we don't handle non-jar dependencies yet. This dependency is [metadata only](https://repo1.maven.org/maven2/com/github/ajalt/clikt/clikt/3.0.1/), so an `extension` is applied during resolution. When we create our dependency query, we are not applying the classifier and extension. This causes a failure because Gradle is looking for a jar and fails.

I did find where to extract this information in #224 but never got around to adding it into the query. It's probably very simple if you'd like to give it a shot. It should just take a little formatting magic in the [query string](https://github.com/ben-manes/gradle-versions-plugin/blob/9effd941ff765dafb3149ac9246da5c7f288e333/src/main/groovy/com/github/benmanes/gradle/versions/updates/Resolver.groovy#L143).

_Originally posted by @ben-manes in https://github.com/ben-manes/gradle-versions-plugin/issues/334#issuecomment-688649827_

**Comment by serebit** [comment] 2020-09-08 14:29
0.31.0 still fails to detect *one* dependency in one of my projects, and that's `com.soywiz.korlibs.klock:klock`. Resolving this issue should fix that.

**Comment by ben-manes** [comment] 2020-09-13 00:32
@sschuberth your issue is due to JCenter which behaves oddly because it only half proxies queries. If you add Maven Central then it works fine. While it is only a metadata dependency, the declaration doesn't have an extension or classifier in the dependency declaration which is what we don't support (e.g. `a:b:1.0@zip`) yet.

@serebit Your issue appears to be due to needing the dependency capabilities copied over. That dependency has a platform capability (e.g. JVM) to select from. I would need a sample project to test against. The [api](https://docs.gradle.org/current/javadoc/org/gradle/api/artifacts/ModuleDependency.html) implies that we could provide the source's `getRequestedCapabilities()` via the target's `capabilities​(configureAction)`. Please provide a minimal failing test build that I can verify a fix against, and open a new issue with those details.

**Closed by ben-manes** 2020-09-13 00:32 UTC

**Comment by sschuberth** [comment] 2020-09-13 07:33
> @sschuberth your issue is due to JCenter which behaves oddly because it only half proxies queries.

Would have have some more details on that, so we could report this to JCenter / JFrog?

**Comment by ben-manes** [comment] 2020-09-13 07:40
The error (`--info`) says that the metadata cannot be fetched, which a cURL verifies.
```
 - com.github.ajalt.clikt:clikt
The exception that is the cause of unresolved state: org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find any matches for com.github.ajalt.clikt:clikt:+ as no versions of com.github.ajalt.clikt:clikt are available.
Searched in the following locations:
  - https://jcenter.bintray.com/com/github/ajalt/clikt/clikt/maven-metadata.xml
```

JCenter proxies explicit versions to Central, but not metadata queries, and can provide stale results from its cache (e.g. `+` resolves only on jcenter). Since that dependency is on Central only, they don't perform the full proxying. If you add Central then Gradle will search it too, and you'll see an update.

**Comment by sschuberth** [comment] 2020-09-13 07:44
Thanks,

BTW, with version 0.32.0 I'm nopw getting something strange:

```
Failed to determine the latest version for the following dependencies (use --info for details):
 - com.github.ajalt.clikt:clikt
 - oss-review-toolkit:test-utils
```

Where `test-utils` is a Gradle project that is part of the same root project, so why is it checked for updates?

**Comment by ben-manes** [comment] 2020-09-13 07:53
I'm not really sure, to be honest. We iterate over all projects to resolve their external dependencies by copying their configuration. It seems the copying confused it, but not sure what the expectation would be either way. The error is,

```
The exception that is the cause of unresolved state: org.gradle.internal.resolve.ModuleVersionResolveException: Could not resolve project :test-utils.
Required by:
    project :test-utils
Caused by: org.gradle.internal.component.model.ConfigurationNotFoundException: Project :test-utils declares a dependency from configuration 'funTestImplementationCopy' to configuration 'default' which is not declared in the descriptor for project :test-utils.
```

**Comment by sschuberth** [comment] 2020-09-13 08:28
> JCenter proxies explicit versions to Central, but not metadata queries, and can provide stale results from its cache (e.g. `+` resolves only on jcenter). Since that dependency is on Central only, they don't perform the full proxying.

I've hijacked this [somewhat related ticket](https://www.jfrog.com/jira/browse/RTFACT-3392), let's see if there's a reaction from JFrog.

**Comment by ben-manes** [comment] 2020-09-13 08:31
Oh, this is probably a side-effect of including the "super configurations" for #334. The `funTestImplementation` configuration extends `testImplementation` which has a dependency on that project. Some interaction that I don't understand results in that error.

**Comment by sschuberth** [comment] 2020-09-13 08:37
Sounds a bit as if the `funTestImplementationCopy` configuration is not variant-aware anymore...

**Comment by ben-manes** [comment] 2020-09-13 08:43
I bet it's because the when we resolve the latest, we filter down to the `ExternalDependency` so it excludes projects, etc. When we add back in the super configuration dependencies, we blindly take all, so it includes the project dependency. If we filter it out then there is a good chance this will go away.

**Comment by sschuberth** [comment] 2020-09-13 08:51
Want me to create a new issue for that? 😉

**Comment by ben-manes** [comment] 2020-09-13 08:53
haha, sure. I just verified it fixed your project and double checking it doesn't regress #334. 😃

**Comment by sschuberth** [comment] 2020-09-13 08:55
Wow, thanks! If you already have the fix, I guess we can spare the issue creation, right?

**Comment by ben-manes** [comment] 2020-09-13 09:14
either way is fine.

When checking against https://github.com/zacsweers/catchup there seems to be a regression in v32 where the super configuration causes some of its dependencies to not resolve, e.g.

```
Caused by: org.gradle.internal.component.NoMatchingConfigurationSelectionException: No matching variant of ru.ldralighieri.corbind:corbind-material:1.3.2 was found. The consumer was configured to find an API of a library, with the library elements 'aar', and its dependencies declared externally, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'release' but:
  - Variant 'compile' capability ru.ldralighieri.corbind:corbind-material:1.3.2 declares an API of a library:
      - Incompatible because this component declares a component, packaged as a jar and the consumer needed a component, with the library elements 'aar'
      - Other compatible attributes:
          - Doesn't say anything about com.android.build.api.attributes.BuildTypeAttr (required 'release')
          - Doesn't say anything about how its dependencies are found (required its dependencies declared externally)
```

So kind of stuck as it seems either we fix for #423 or revert it, unless there's more metadata (like constraints) we need to copy over?

**Comment by ben-manes** [comment] 2020-09-13 09:32
I think unwrangling this is going to be hard, as either approach results in some variant failure. There might be a partial fix for #423 by special casing Kotlin's stdlib and not bringing everything else across. A new ticket is probably worthwhile since its late again here.

**Comment by ben-manes** [comment] 2020-09-13 09:38
Okay, that did it. So I'll just keep any super configuration's external dependency that belongs to the group `org.jetbrains.kotlin` and both of your projects resolve. Hopefully that's good enough for me to be inactive for another year. 
 :stuck_out_tongue:

**Comment by ben-manes** [comment] 2020-09-13 09:48
okay, v33 is being released 🤞

**Comment by serebit** [comment] 2020-09-14 14:54
Sadly, v33 doesn't fix `com.soywiz.korlibs.klock:klock`. I'll see to creating a small reproduction build.

**Comment by ben-manes** [comment] 2020-11-02 10:28
@serebit Please try 0.34, which has an addition fix for Kotlin MPP (special case copy of their legacy metadata).
