### ISSUE TITLE
Wrong version comparison for Spring Framework

### ISSUE THREAD

**Issue by pkubowicz** [ben-manes/gradle-versions-plugin#73] opened 2015-08-07 11:13 UTC
build.gradle:
```
buildscript {
    repositories {
        jcenter()
    }

    dependencies {
        classpath 'com.github.ben-manes:gradle-versions-plugin:0.11.3'
    }
}

apply plugin: 'java'
apply plugin: 'com.github.ben-manes.versions'

repositories {
    mavenCentral()
}

dependencies {
    compile(group: 'org.springframework', name: 'spring-core', version:'4.2.0.RELEASE')
}
```

Buggy report:

```
% gradle depUp
:dependencyUpdates

------------------------------------------------------------
: Project Dependency Updates (report to plain text file)
------------------------------------------------------------

The following dependencies are using the latest milestone version:
 - com.github.ben-manes:gradle-versions-plugin:0.11.3

The following dependencies have later milestone versions:
 - org.springframework:spring-core [4.2.0.RELEASE -> 4.2.0.RC3]
```

`4.2.0.RELEASE` should be considered later than `4.2.0.RC3`.

**Comment by ben-manes** [comment] 2015-08-07 16:51
Unfortunately this is an issue with Ivy's implementation of the Maven versioning scheme. Since Gradle uses Ivy's comparitor and we use the one provided by Gradle for consistency. Ideally this issue should be fixed by Gradle, since it also affects other usages such as `version: '+'` and component selection rules.

I'd like to see Gradle port Maven's [ComparableVersion](https://github.com/apache/maven/blob/master/maven-artifact/src/main/java/org/apache/maven/artifact/versioning/ComparableVersion.java) to follow its rules. There's been minor discussion by the Gradle team of making the comparator pluggable, since it currently doesn't follow the semantic versioning rules.

Please consider bringing this up on the [Gradle forum](https://discuss.gradle.org). If enough people do maybe it will rise in their priority queue.

**Comment by pkubowicz** [comment] 2015-08-10 11:42
Thank you for the clarification. I opened [a disussion on Gradle forum](https://discuss.gradle.org/t/wrong-version-comparison-for-maven-affecting-spring/11066).

**Comment by ben-manes** [comment] 2016-01-13 06:29
I'm going to close this as a Gradle problem that they have acknowledged, but not fixed. The best you can do is use a `resolutionStrategy` to reject release candidates, if desired. Otherwise its not a bug we can fix without rewriting Gradle's dependency management.

**Closed by ben-manes** 2016-01-13 06:29 UTC
