### ISSUE TITLE
no repositories are defined

### ISSUE THREAD

**Issue by tprochazka** [ben-manes/gradle-versions-plugin#71] opened 2015-07-20 20:28 UTC
I used this plugin for long time, but I don't know when, but now this happen to me.
But my repositories is normally setuped, project is possible to build normaly.
Do you know why?

```
All dependencies have later versions.

All dependencies are using the latest milestone versions.

Failed to determine the latest version for the following dependencies (use --info for details):
 - com.android.support:appcompat-v7
The exception that is the cause of unresolved state: Cannot resolve external dependency com.android.support:appcompat-v7:+ because no repositories are defined.
 - com.android.support:appcompat-v7
The exception that is the cause of unresolved state: Cannot resolve external dependency com.android.support:appcompat-v7:+ because no repositories are defined.
 - com.android.support:appcompat-v7
The exception that is the cause of unresolved state: Cannot resolve external dependency com.android.support:appcompat-v7:+ because no repositories are defined.
 - com.android.support:appcompat-v7
The exception that is the cause of unresolved state: Cannot resolve external dependency com.android.support:appcompat-v7:+ because no repositories are defined.
 - com.android.support:cardview-v7
The exception that is the cause of unresolved state: Cannot resolve external dependency com.android.support:cardview-v7:+ because no repositories are defined.
 - com.avast:android-styled-dialogs
The exception that is the cause of unresolved state: Cannot resolve external dependency com.avast:android-styled-dialogs:+ because no repositories are defined.
 - com.avast:android-styled-dialogs
The exception that is the cause of unresolved state: Cannot resolve external dependency com.avast:android-styled-dialogs:+ because no repositories are defined.
 - com.avast:android-styled-dialogs
The exception that is the cause of unresolved state: Cannot resolve external dependency com.avast:android-styled-dialogs:+ because no repositories are defined.
```

**Comment by ben-manes** [comment] 2015-07-20 20:34
Are you using 0.10.x or 0.11.x? There were a lot of changes in 11 and some fixes were not pushed out into a release yet. Its okay to downgrade if you are using 11, since there was a lot of changes, and I got busy so I never finished all that I had planned.

If that solves your problem, I'd also appreciate if you can put a sample build file that shows the problem. I can test to see if that's fixed on master or not. If so, I suspect its due to #66 exposing a bug in Gradle.

**Comment by tprochazka** [comment] 2015-07-21 07:07
Yes. I'm using 0.11.3.
But I have own corporate plugin which setup repositories and some default plugins for me.
So it also can be reason, but everything else works correctly.

**Comment by tprochazka** [comment] 2015-07-21 18:18
So problem is not directly in the 0.11.3 version but in the gradle, it works with Gradle 2.3, but not in Gradle 2.4, also older version 0.10.1 doesn't work with Gradle 2.3.

**Comment by ben-manes** [comment] 2015-07-21 18:22
Do you think you could make a build file that reproduces the problem that you can share? If so then I can help investigate a fix.

**Comment by tprochazka** [comment] 2015-07-22 18:35
I will try to make it.

**Comment by tprochazka** [comment] 2015-09-18 22:29
I tried investigate it and it looks that your plugin is not able to recognize repositories which is provided (setuped) by another plugin. 

For example I'm using init gradle script which look like this
```
    initscript {
        buildscript {
            repositories {
                mavenLocal()
                maven { url 'http://myrepourl/repo' }
            }
            dependencies {
                classpath 'com.my.gradle:gradle-build-plugin:0.9+'
            }
        }
    }

    allprojects { apply plugin: com.my.gradle.buildplugin.InitPlugin }
```

And InitPlugin itself setup repository in the apply() method.
If I turn if off and move repository setup directly to the build script it works correctly.

But for example android dependencies are still not resolved because android gradle plugin added android SDK repo also itself at runtime.

I don't understand why, whole project is setuped before you start examine repos, all plugin must be applied already. It worked correctly until Gradle 2.4. 

I tested it now by Gradle 2.7 and it still doesn't works.

**Comment by ben-manes** [comment] 2015-09-18 22:46
Thanks for looking into this.

We walk all projects for their buildscript and project-level configurations. We don't have any special handling for initscript, so maybe there is some API calls we need to make to capture more information. I thought that all the necessary information would be copied into the project configurations, but I guess not. There's a configuration hierarchy concept ("super configuration") so maybe when we lose something inherited?

Do you think you could take your example and make a spock unit test or a simple example? That would help me focus on figuring out a fix rather than trying to reproduce the problem.

**Comment by ben-manes** [comment] 2015-09-25 23:02
I haven't gotten much farther with your sample other than finding that your plugin's attempt to remove duplicate repositories somehow confuses Gradle. The plugin lists the repositories it thinks its using, `--info`, and the resolution thinks there are none.

In my experience RepositoryHandler has been flaky with respect to ad hoc adds and removals. It already is smart for core repository types (`jcenter`, `mavenCeneral`, `mavenLocal`) and less so for custom repositories. In my experience the best solution is to use a corporate virtual repository (e.g. Artifactory) as the sole repository in your build files. This has a number of benefits, including removing the need for your init plugin (and its `eliminateDuplicates`) entirely.

**Comment by ben-manes** [comment] 2016-01-13 04:49
Fixing #66 resolves this issue. I ran your sample with `0.11.3` to reproduce the bad results. Then I changed it to `+` and added `mavenLocal()`. The report resolved the dependencies correctly.

**Closed by ben-manes** 2016-01-13 04:49 UTC
