### ISSUE TITLE
Possible regression in 0.28.0 with Gradle 5.1.1, dependencyUpdates fails with ref to org/gradle/api/artifacts/CapabilitiesResolution

### ISSUE THREAD

**Issue by JoergHeinicke5005** [ben-manes/gradle-versions-plugin#386] opened 2020-03-05 23:17 UTC
The release notes on v 0.28.0 state:
```
Note: the Gradle Versions Plugin now requires at least Gradle 5.0 to function.
```

When we execute dependencyUpdates task in Gradle 5.1.1 in our project it fails though with
```
> Task :dependencyUpdates FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':dependencyUpdates'.
> org/gradle/api/artifacts/CapabilitiesResolution

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':dependencyUpdates'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:95)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:91)
...
Caused by: java.lang.NoClassDefFoundError: org/gradle/api/artifacts/CapabilitiesResolution
        at java.desktop/com.sun.beans.introspect.MethodInfo.get(MethodInfo.java:71)
        at java.desktop/com.sun.beans.introspect.ClassInfo.getMethods(ClassInfo.java:71)
        at com.github.benmanes.gradle.versions.updates.resolutionstrategy.ResolutionStrategyWithCurrent.$getStaticMetaClass(ResolutionStrategyWithCurrent.groovy)
        at com.github.benmanes.gradle.versions.updates.resolutionstrategy.ResolutionStrategyWithCurrent.<init>(ResolutionStrategyWithCurrent.groovy)
        at com.github.benmanes.gradle.versions.updates.Resolver$1.execute(Resolver.groovy:192)
        at com.github.benmanes.gradle.versions.updates.Resolver$1.execute(Resolver.groovy)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.resolutionStrategy(DefaultConfiguration.java:992)
        at com.github.benmanes.gradle.versions.updates.Resolver.addCustomResolutionStrategy(Resolver.groovy:189)
        at com.github.benmanes.gradle.versions.updates.Resolver.createLatestConfiguration(Resolver.groovy:137)
        at com.github.benmanes.gradle.versions.updates.Resolver.resolve(Resolver.groovy:76)
        at com.github.benmanes.gradle.versions.updates.DependencyUpdates.resolve(DependencyUpdates.groovy:85)
        at com.github.benmanes.gradle.versions.updates.DependencyUpdates.access$0(DependencyUpdates.groovy)
        at com.github.benmanes.gradle.versions.updates.DependencyUpdates$_resolveProjects_closure6$_closure10.doCall(DependencyUpdates.groovy:75)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at com.github.benmanes.gradle.versions.updates.DependencyUpdates$_resolveProjects_closure6.doCall(DependencyUpdates.groovy:70)
        at com.github.benmanes.gradle.versions.updates.DependencyUpdates$_resolveProjects_closure6.call(DependencyUpdates.groovy)
        at com.github.benmanes.gradle.versions.updates.DependencyUpdates.resolveProjects(DependencyUpdates.groovy:67)
        at com.github.benmanes.gradle.versions.updates.DependencyUpdates.run(DependencyUpdates.groovy:55)
        at com.github.benmanes.gradle.versions.updates.DependencyUpdatesTask.dependencyUpdates(DependencyUpdatesTask.groovy:100)
...
Caused by: java.lang.ClassNotFoundException: org.gradle.api.artifacts.CapabilitiesResolution
        ... 93 more
```
while it still works with 0.27.0.

Looking at https://docs.gradle.org/current/javadoc/org/gradle/api/artifacts/CapabilitiesResolution.html it looks like the class is only available since Gradle 5.6.

We do have a custom resolution strategy but I have no clue how CapabilitiesResolution comes into the picture with 0.28.0.

**Comment by ben-manes** [comment] 2020-03-06 00:13
I bet it must be due to `@CompileStatic` which would be like Java's compilation.  That could pull into the byte code the signatures of the class version we compiled against, whereas previously it was only interpreted (but type checked). (Think animal sniffer for jdk cross compilation)

/cc @SUPERCILEX

**Comment by anuraaga** [comment] 2020-03-06 03:38
I don't think I've seen projects using a more modern Gradle than their minimum version supported probably for this reason. Wonder if there is an animal sniffer type mechanism to facilitate it though.

That being said it's surprising that our integration test doesn't catch it. I guess Gradle test runner must ignore compilestatic 😥

**Comment by xenomachina** [comment] 2020-03-09 21:24
We're running into this same issue when using Gradle 5.4.1.

**Comment by ben-manes** [comment] 2020-03-10 02:22
Can you please provide us a minimal build that fails? That will help us to validate a fix and release for you.

We could either revert this class to `@TypeChecked` or downgrade the build. Which do you prefer @anuraaga?

**Comment by SUPERCILEX** [comment] 2020-03-10 03:28
Just saw this. 😬 My vote would be marking it as `@TypeChecked` again. Should I send up a PR?

**Comment by ben-manes** [comment] 2020-03-10 03:31
Yep, that would be great. I think we should get try to reproduce the failure first, though. Even better if we can add as an integration test, e.g. external build call, since this seems really easy to reintroduce by mistake.

**Comment by anuraaga** [comment] 2020-03-10 05:51
Yeah thought about it and `@TypeChecked` seems better - downgrading the build and sticking with `CompileStatic` would probably make supporting old / new APIs in the same plugin more complicated than its worth.

**Comment by jaredsburrows** [comment] 2022-05-03 21:12
@JoergHeinicke5005 Are you still seeing this? We have a test with Gradle `5.1.1` here: https://github.com/ben-manes/gradle-versions-plugin/blob/master/src/test/groovy/com/github/benmanes/gradle/versions/DifferentGradleVersionsSpec.groovy#L101.

If you are still able to repro, please leave a comment.

**Closed by jaredsburrows** 2022-05-03 21:12 UTC
